backend/ImaGen/ImaGen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imagenapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
     
    
] 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/ImaGen/imagenapp/forms.py
from django import forms
from .models import Upload, ImageConvert, ImageFilter


# Img Gen Form
class ImgGenForm(forms.Form):
    text = forms.CharField(max_length=500, initial="A raccoon astronaut with the cosmos reflecting on the glass of his helmet dreaming of the stars.")

# Img Gen Dalle2 Form
class ImgGenDalleForm(forms.Form):
    text = forms.CharField(max_length=500, initial="A Pig In Sunglasses Wearing An Aloha Shirt Blowing In The Wind While Driving A Motorcycle Through The Desert.")


# QR Gen Form
class QRGenForm(forms.Form):
    text = forms.CharField(max_length=500, initial="Hola, 🤗")


# Image 2 PDF Form
class ImageToPDFForm(forms.Form):
    image = forms.ImageField()


# Remove Background
class RemoveBackgroundForm(forms.Form):
    image = forms.ImageField()


# Colorize Image Filter Form
FILTER_COLOR = (
    ('sepia', 'Sepia'),
    ('red', 'Red'),
    ('skyblue', 'Sky Blue'),
    ('darkpink', 'Dark Pink'),
    ('lemonyellow', 'Lemon Yellow'),
    ('darkgrey', 'Dark Grey'),
)

class ColorizeFilterForm(forms.Form):
    image = forms.ImageField()
    filter_color = forms.ChoiceField(
        required=True,
        choices=FILTER_COLOR
    )


# Image Convert Form
CONVERT = (
    ('WEBP', 'WEBP'),
    ('PNG', 'PNG'),
    ('JPG', 'JPG'),
    ('JPEG', 'JPEG')
)

class ImageConvertForm(forms.Form):
    image = forms.ImageField()
    convert = forms.ChoiceField(
        required=True,
        choices=CONVERT
    )


# Reduce Image Quality Form
class ImageQualityForm(forms.Form):
    image = forms.ImageField()
    quality = forms.CharField(max_length=200, initial=95)


# Rotate Image Form
class ImageRotateForm(forms.Form):
    image = forms.ImageField()
    angle = forms.CharField(max_length=10, initial="90")
    expand = forms.BooleanField(required=False, initial=False)


# Flip Image Form
FLIP_OPTIONS = (
    ('FLIP_TOP_BOTTOM', 'Flip Top To Bottom'),
    ('FLIP_LEFT_RIGHT', 'Flip Left To Right'),
    ('ROTATE_90', 'Rotate 90 degree'),
    ('ROTATE_180', 'Rotate 180 degree'),
    ('ROTATE_270', 'Rotate 270 degree'),
    ('TRANSVERSE', 'Transverse'),
)

class ImageFlipForm(forms.Form):
    image = forms.ImageField()
    flip_options = forms.ChoiceField(
        required=True,
        choices=FLIP_OPTIONS
    )


########################################
class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = '__all__'

# class ImageConvertForm(forms.ModelForm):
#     class Meta:
#         model = ImageConvert
#         fields =  '__all__'

class ImageFilterForm(forms.ModelForm):
    class Meta:
        model = ImageFilter
        fields =  '__all__'


# Extract Img From
class ExtractImgFrom(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

backend/ImaGen/templates/colorize-filter.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Colorize Filters {% endblock %}
{% block content %}

<!-- Colorize Filters -->
<div class="container my-5">
  <div class="row g-3">
    <div class="col-12 col-sm-12 col-md-6">
      <div class="card border-1 border rounded p-3">
        <form action="{% url 'colorize_filter' %}" method="POST" enctype="multipart/form-data">
          <h3 class="text-center mx-auto">Colorize Filters</h3>
          {% csrf_token %}
          {{form|crispy}}
          <button class="btn btn-success w-100 btn-lg" type="submit">
            <i class="fa-solid fa-refresh"></i>&nbsp;
            Apply Filter</button>
        </form>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-6">
      <div class="card border-0">
        <img id="imgPreview" alt="Preview Image" style="display: none;">
      </div>
      {% if uploaded_file_url %}
      <div class="card border rounded" id="downloadImage">
        <img 
          class="card-img-top"
          src="/media/{{ img_name }}" 
          alt="download image">
        <div class="p-2 mt-2">
          <a class="btn btn-dark w-100 btn-lg" href="{{ uploaded_file_url }}" download>
            <i class="fa-solid fa-download"></i> &nbsp; 
            Download 
          </a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}
{% block javascript %}
<script>

  $(document).ready(() => {
    // set the select input
    let action = "{{action|lower}}";
    $("#id_filter_color").val(action);

    // image preview
    $('#id_image').change(function () {
      const file = this.files[0];
      if (file) {
        let reader = new FileReader();
        reader.onload = function (event) {
          $('#imgPreview').attr('src', event.target.result);
          $("#imgPreview").css("display", "block");
          $("#downloadImage").css("display", "none");
        }
        reader.readAsDataURL(file);
      }
    });

  });
</script>
{% endblock %}

backend/ImaGen/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Dashboard {% endblock %}
{% block content %}
 

<div class="container mt-3 mb-5 position-relative ">
  <!-- Toast Message Popup -->
  <div class="toast hide position-absolute end-0 fixed " id="toast" style="background-color: #e9fff7;">
    <div class="toast-header">
      <strong class="me-auto">ImaGen</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast"></button>
    </div>
    <div class="toast-body">
      <p class="fw-bold text-success" id="toastMsg" >
      </p>
    </div>
  </div>

  <!-- Left section -->
  <div class="row d-flex align-center">
    <div class="col-lg-3">
      <div class="row">
        <div class="d-flex flex-column flex-shrink-0 p-3 "  >
          <div class="d-flex align-items-center g-3">
            <div class="col-lg-4">
              <img src="{{ user.photo.url }}" alt="" width="100px" height="100px"
              class="rounded-circle shadow-sm" style="object-fit: cover; object-position: center;" id="userImage"/>
            </div>
            <div class="col-lg-8 ms-3">
              <a href="{% url 'profile' user.username %}" class="fs-3 fw-bold text-dark">{{ user.name | title }}</a>
              <p class="text-light-dark">
                {{user.email}}
              </p>
            </div>
          </div>
          <hr />
          <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
              <a href="#" class="nav-link text-dark" aria-current="page" style="background-color:#D9E2EC"
              id="profileBtn">
              <i class="fa-solid fa-user-astronaut"></i> &nbsp;Public Profile
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link text-dark" aria-current="page" id="accountBtn">
              <i class="fa-solid fa-gear"></i> &nbsp;Account
            </a>
          </li>
        </ul>
        <hr />
      </div>
    </div>
  </div>
  <!-- end Left section -->
  
  <!-- Right section -->
  <div class="col-lg-9"> 
    <div class="row p-3">

      <!-- Public Profile Section -->
      <div class="row fade show" style="display: block" id="profile">
        <h4>Public Profile</h4>
        <hr />
        <form id="updateProfile" enctype="multipart/form-data">
          {% csrf_token %}
          <!-- Name -->
          <div class="mb-3">
            <label for="nameInput" class="form-label"> Name </label>
            <input type="text" class="form-control" id="nameInput" aria-describedby="nameHelp" value="{{ user.name }}" name="name"/>
            <div id="nameHelp" class="form-text">
              Your name may appear around ImaGen where you show or are mentioned.
              You can remove it at any time.
            </div>
          </div>

          <!-- Photo -->
          <div class="mb-3">
            <label for="imageInput" class="form-label"> Photo </label>
            <input type="file" class="form-control" id="imageInput" aria-describedby="imageHelp" value="{{ user.name }}" name="image"/>
            <div id="imageHelp" class="form-text">
              Your profile photo.
            </div>
          </div>



          <!-- Email -->
          <div class="mb-3">
            <label for="emailInput" class="form-label"> Email </label>
            <input type="email" class="form-control" id="emailInput" aria-describedby="emailHelp"
            value="{{ user.email }}" readonly disabled />
            <div id="emailHelp" class="form-text">
              You have set your email address to private. To toggle email privacy,
              go to email settings and uncheck "Keep my email address private."
            </div>
          </div>

          <!-- Bio -->
          <div class="mb-3">
            <label for="bioInput" class="form-label"> Bio </label>
            <input type="text" class="form-control" id="bioInput" aria-describedby="bioHelp" value="{{user.bio}}" name="bio"/>
            <div id="bioHelp" class="form-text">
              You can @mention other users and organizations to link to them.
            </div>
          </div>

          <!-- Portfolio -->
          <div class="mb-3">
            <label for="portfolioInput" class="form-label"> Portfolio URL </label>
            <input type="text" class="form-control" id="bioInput" aria-describedby="portfolioHelp" value="{{user.url}}" name="url" />
            <div id="portfolioHelp" class="form-text"></div>
          </div>

          <!-- Location -->
          <div class="mb-3">
            <label for="locationInput" class="form-label"> Location </label>
            <input type="text" class="form-control" id="locationInput" aria-describedby="locationHelp"
            value="{{user.location}}" name="location"/>
            <div id="locationHelp" class="form-text"></div>
          </div>

          <button type="submit" class="btn btn-success  fw-bold rounded-1">
            Update Profile
          </button>
          <a  href="{% url 'home' %}" class="btn btn-light">
            Cancel
          </a>
        </form>
      </div>

      <!-- Account Section -->
      <div class="row fade show" style="display: none" id="account">
        <form action="{% url 'delete_account' %}" method="POST">
          {% csrf_token %}
          <h4 class="text-danger fw-bold">Delete Account</h4>
          <hr />
          <p class="text-dark">
            Once you delete your account, there is <b>no going back</b>. Please be
            certain.
          </p>
          <button class="btn  btn-danger mt-3 rounded-1" type="submit">
            I'm Sure, Delete My Account!
          </button>
        </form>
      </div>

    </div>
  </div>
  <!-- end Right section -->

</div>
 
 
{% endblock %} 


{% block javascript %}
  <script>
   

    $(document).ready(() => {
      
     
      // profile
      $("#profileBtn").click(function () {
        $("#profile").css("display", "block");
        $("#account").css("display", "none");
        $("#profileBtn").css("background-color", "#D9E2EC");
        $("#accountBtn").css("background-color", "unset");
      });

      // account
      $("#accountBtn").click(function () {
        $("#profile").css("display", "none");
        $("#account").css("display", "block");
        $("#accountBtn").css("background-color", "#D9E2EC");
        $("#profileBtn").css("background-color", "unset");
      });


      // update profile
      $("#updateProfile").submit(function (e) {
      e.preventDefault();
      // var serializedData = $(this).serialize();
      var serializedData = new FormData(this);
      $.ajax({

          type: 'POST',
          url: "{% url 'update_profile' %}",
          data: serializedData,
          cache:false,
          contentType: false,
          processData: false,

          success: function (response) {

            $("#toast").removeClass('hide');
            $("#toast").addClass('show');
            $("#toastMsg").html(response['messages']);
            $("#userImage").attr("src",  response['image_url']);

          },

          error: function (response) {
              alert(response);
          }

        });
      })
    });
  </script>
{% endblock %}

backend/ImaGen/templates/extract-image.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Extract Image From PDF {% endblock %}
{% block content %}

<!-- Reduce Image Quality -->
<div class="container my-5">
    <div class="row g-3">
        <div class="col-12 col-sm-12 col-md-6">
            <div class="card border-1 rounded p-3">
                <form action="{% url 'extract' %}" method="POST" enctype="multipart/form-data">
                    <h3 class="text-center mx-auto">Extract Images From PDF</h3>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-success w-100 btn-lg" type="submit">
                        <i class="fa-solid fa-refresh"></i>&nbsp;
                        Extract</button>
                </form>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6">
            <div class="row">
                {% for key, image in images.items %}
                <div class="card border-1 rounded-1" >
                    <img  class="card-img-top" src="{{ image.uploaded_file_url }}" alt="download image">
                    <div class="card-body">
                        <a class="btn btn-dark w-100 btn-lg" href="/media/{{ image.img_name }}" download>
                            <i class="fa-solid fa-download"></i> &nbsp;
                            Download
                        </a>
                    </div>
                  </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
<script>

    $(document).ready(() => {

        // image preview
        $('#id_image').change(function () {
            const file = this.files[0];
            if (file) {
                let reader = new FileReader();
                reader.onload = function (event) {
                    $('#imgPreview').attr('src', event.target.result);
                    $("#imgPreview").css("display", "block");
                    $("#downloadImage").css("display", "none");
                }
                reader.readAsDataURL(file);
            }
        });

    });
</script>
{% endblock %}

backend/ImaGen/templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Feedback {% endblock %}
{% block content %}


<div class="container mt-2 mb-5 p-3 ">
    <div class="row">
        <div class="card border-1 border-success shadow-sm p-3 mx-auto"
          style="width: 800px;  background-color: #f9f9fa;">
            <div class="row g-3">
                <div class="col-lg-6 d-flex">
                    <img src="{% static 'images/hero9.png' %}" class="img-fluid rounded-start" alt="Feedback Image">
                </div>
                <div class="col-lg-6">
                    <div class="card-body p-3">
                        <h4 class="card-title text-center">Feedback</h4>
                        <hr>
                        <form action="{% url 'feedback' %}" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-success rounded-1 px-3">
                                Send Message
                            </button>
                            <a href="{% url 'home' %}" class="btn btn-light rounded-1">
                                Cancel
                            </a>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}


{% block javascript %}

{% endblock %}

backend/ImaGen/templates/image-convert.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}  Convert Image {{action|upper}} {% endblock %}
{% block content %}

<!-- Image To PDF -->
<div class="container my-5">
    <div class="row g-3">
        <div class="col-12 col-sm-12 col-md-6">
            <div class="card border-1 rounded p-3">
                <form action="{% url 'image_convert' %}" method="POST" enctype="multipart/form-data">
                    <h3 class="text-center mx-auto">Convert Image To {{action|upper}}</h3>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-success w-100 btn-lg" type="submit">
                        <i class="fa-solid fa-refresh"></i>&nbsp;
                        Convert Image</button>
                </form>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6">
            <div class="card border-0">
                <img id="imgPreview" alt="Preview Image" style="display: none;">
            </div>
            {% if uploaded_file_url %}
            <div class="card border rounded" id="downloadImage">
                <img 
                  class="card-img-top"
                  src="/media/{{ img_name }}" 
                  alt="download image">
                <div class="p-2 mt-2">
                  <a class="btn btn-dark w-100 btn-lg" href="{{ uploaded_file_url }}" download>
                    <i class="fa-solid fa-download"></i> &nbsp; 
                    Download 
                  </a>
                </div>
              </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
<script>

    $(document).ready(() => {
      // set the select input
      let action = "{{action|upper}}";
      $("#id_convert").val(action);
  
      // image preview
      $('#id_image').change(function () {
        const file = this.files[0];
        if (file) {
          let reader = new FileReader();
          reader.onload = function (event) {
            $('#imgPreview').attr('src', event.target.result);
            $("#imgPreview").css("display", "block");
            $("#downloadImage").css("display", "none");
          }
          reader.readAsDataURL(file);
        }
      });
  
    });
  </script>
{% endblock %}

backend/ImaGen/templates/image-gen.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}  AI Image Generator  {% endblock %}
{% block content %}
<style>
    body {
        background-color: #272e34  !important;
    }
</style>

<!-- AI Image Generator -->
<div class="container my-5">
    <div class="row g-3 text-light">
        <div class="col-12 col-sm-12 col-md-6" >
            <div class="card showdow-lg rounded p-3 bg-dark" style="box-shadow: rgba(9, 197, 216, 0.62) 0px 4px 10px 0px;">
                <form action="{% url 'image_gen' %}" method="POST">
                    <h3 class="text-center mx-auto">
                        AI Image Generator
                    </h3>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-outline-info w-100 btn-lg" type="submit">
                        <i class="fa-solid fa-robot"></i>&nbsp;
                       Generate Image
                    </button>
                </form>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6">
            {% if uploaded_file_url %}
            <div class="card showdow-lg rounded p-3 bg-dark text-light d-block text-center" style="box-shadow: rgba(9, 197, 216, 0.62) 0px 4px 10px 0px;">
                <img 
                class="card-img-top"
                src="/media/{{ img_name }}" 
                alt="download image"
                style="width: 300px;"
                >
                <div class="p-2 mt-2">
                    <h4 class="text-center mx-auto">AI Image Generator</h4>
                    <h5 class="fw-bold text-danger my-3">{{text|title}}</h5>
                    <a class="btn btn-info w-100 btn-lg" href="/media/{{ img_name }}" download><i
                          class="fa-solid fa-download"></i> &nbsp; Download </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
 

backend/ImaGen/templates/image-modal.html
<div id="popup" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Close
          </button>
        </div>
      </div>
    </div>
  </div>

backend/ImaGen/templates/image-quality.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Reduce Image Quality {% endblock %}
{% block content %}

<!-- Reduce Image Quality -->
<div class="container my-5">
  <div class="row g-3">
    <div class="col-12 col-sm-12 col-md-6">
      <div class="card border-1 rounded p-3">
        <form action="{% url 'image_quality' %}" method="POST" enctype="multipart/form-data">
          <h3 class="text-center mx-auto">Reduce Image Quality</h3>
          {% csrf_token %}
          {{form|crispy}}
          <button class="btn btn-success w-100 btn-lg" type="submit">
            <i class="fa-solid fa-arrow-down-wide-short"></i>&nbsp;
            Reduce Quality</button>
        </form>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-6">
      <div class="card border-0">
        <img id="imgPreview" alt="Preview Image" style="display: none;">
      </div>
      {% if uploaded_file_url %}
      <div class="card border rounded" id="downloadImage">
        <img class="card-img-top" src="/media/{{ img_name }}" alt="download image">
        <div class="p-2 mt-2">
          <a class="btn btn-dark w-100 btn-lg" href="{{ uploaded_file_url }}" download>
            <i class="fa-solid fa-download"></i> &nbsp;
            Download
          </a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}
{% block javascript %}
<script>

  $(document).ready(() => {

    // image preview
    $('#id_image').change(function () {
      const file = this.files[0];
      if (file) {
        let reader = new FileReader();
        reader.onload = function (event) {
          $('#imgPreview').attr('src', event.target.result);
          $("#imgPreview").css("display", "block");
          $("#downloadImage").css("display", "none");
        }
        reader.readAsDataURL(file);
      }
    });

  });
</script>
{% endblock %}

backend/ImaGen/templates/image-remove-background.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Remove Background From Image {% endblock %}
{% block content %}

<!-- Remove Background From Image -->
<div class="container my-5">
    <div class="row g-3">
        <div class="col-12 col-sm-12 col-md-6">
            <div class="card border-1 rounded p-3">
                <form action="{% url 'image_removebg' %}" method="POST" enctype="multipart/form-data">
                    <h3 class="text-center mx-auto">Remove Background Image</h3>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-success w-100 btn-lg" type="submit">
                        <i class="fa-solid fa-wand-magic-sparkles"></i>&nbsp;
                        Remove Background</button>
                </form>
            </div>
        </div>
        <style>
        .transparency-grid {
                background-color: #fff;
                background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3LjkzNyA3LjkzOCIgaGVpZ2h0PSIzMCIgd2lkdGg9IjMwIj48cGF0aCBwYWludC1vcmRlcj0ic3Ryb2tlIGZpbGwgbWFya2VycyIgZD0iTS4wMTQuMDE0SDMuOTdWMy45N0guMDE0ek0zLjk3IDMuOTY4aDMuOTU0djMuOTU1SDMuOTd6IiBmaWxsPSIjZWVlZmYwIi8+PC9zdmc+");
                background-size: 25px;
        }
        </style>
             
        <div class="col-12 col-sm-12 col-md-6">
            <div class="row ms-2">
                <div class="card border-0 p-0 shadow-sm" style="width: 500px; height:300px; overflow:hidden;" id="imgPreviewBlock">
                    <img id="imgPreview" alt="Preview Image" style="width:100%;">
                </div>
                {% if uploaded_file_url %}
                <div class="card border-1 p-0 shadow-sm" id="downloadImage">
                    <img src="{{ uploaded_file_url }}" style="max-height: 50vh;" class="img-fluid transparency-grid card-img-top" ondragstart="return false;" data-hj-suppress="true" data-v-1ab68894="" alt="download image">
                    <div class="card-body">
                        <a class="btn btn-dark w-100 btn-lg" href="/media/{{ img_name }}" download>
                            <i class="fa-solid fa-download"></i> &nbsp;
                            Download
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
<script>

    $(document).ready(() => {
        $("#imgPreviewBlock").css("display", "none");

        // image preview
        $('#id_image').change(function () {
            const file = this.files[0];
            if (file) {
                let reader = new FileReader();
                reader.onload = function (event) {
                    $('#imgPreview').attr('src', event.target.result);
                    $("#imgPreviewBlock").css("display", "block");
                    $("#downloadImage").css("display", "none");
                }
                reader.readAsDataURL(file);
            }
        });

    });
</script>
{% endblock %}

backend/ImaGen/templates/messages.html
<div class="container mt-2">
  {% for msg in messages %}
  <div class="alert {{ msg.tags }} alert-dismissible fade show" role="alert">
      {{ msg }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
</div>

backend/ImaGen/templates/temp.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Temp {% endblock %}
{% block content %}

<div class="row" data-bs-theme="dark">
    <div class="col-6">
        <div class="card border rounded p-3" data-bs-theme="dark">
          <form action="{% url 'temp' %}" method="POST" enctype="multipart/form-data"  id="imageForm">
              {% csrf_token %}
                <h3 class="text mx-auto">Temp_name</h3>
                <input type="file" name="image" class="form-control" accept="image/*" id="id_image" required="">
                <br/>
                <label for="exampleColorInput" class="form-label">Filter Color Picker</label>
                
                
                <button class="btn btn-success w-100 btn-lg" type="submit">
                    <i class="fa-solid fa-arrow-down-wide-short"></i>&nbsp;
                    Button_name</button>
            </form>
        </div>
    </div>
    <div class="col-6">
      
      {% if True %}
      <div class="card border rounded ">
          <img style="height: 300px;" src="{{ uploaded_file_url }}" alt="download image" id="imgPreview">
          <div class="p-2 mt-2">
             <button class="btn btn-info btn-lg w-100 my-3">
              <i class="fa-solid fa-refresh"></i> &nbsp;Update Preview
             </button>
              <a class="btn btn-dark w-100 btn-lg" href="{{ uploaded_file_url }}" download><i
                    class="fa-solid fa-download"></i> &nbsp; Download </a>
          </div>
      </div>
      {% endif %}
  </div>
</div>
 

{% endblock %}
{% block jsscript %}
<script>
    $(document).ready(()=>{
      $('#id_image').change(function(){
        const file = this.files[0];
        //console.log(file);
        if (file){
          let reader = new FileReader();
          reader.onload = function(event){
            console.log(event.target.result);
            $('#imgPreview').attr('src', event.target.result);
          }
          reader.readAsDataURL(file);
        }
      });

      function updateImagePreview(uploaded_file_url){
        $('#imgPreview').attr('src', uploaded_file_url);
      }

      $('#color').change(function(){
        
        // var serializedData = new FormData(document.querySelector("form"))
        // var serializedData = new FormData('form')
        // var serializedData = $('#imageForm').serialize();
        // console.log(serializedData)
        $.ajax({
        type: 'POST',
        url: "{% url 'temp_ajax' %}",
        data: new FormData(document.querySelector("form")),
        contentType: false,       
        cache: false,             
        processData:false, 
        success: function (response) {
           
          alert('success!')
          uploaded_file_url = response['uploaded_file_url'];
          updateImagePreview(uploaded_file_url)
          console.log(response)
        },

        error: function (response) {
            alert(response["error"]);

        }

        })

      });

    });
</script>
{% endblock %}